# Generated by Django 4.2.20 on 2025-04-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_at_task_description_task_timer_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
